### ISSUE TITLE
缺少resnet50的代码

### ISSUE THREAD

**Issue by fupiao1998** [zhaozhirui/CTDNet#1]
您好，在您开源的代码中，resnet中的参数（layer数量，channel数量）是写的固定的resnet18的参数，而没有resnet50的相应代码，希望能把这部分代码开源一下，要不然加载不进来数据集（捂脸），谢谢啦。

**Comment by zhaozhirui** [comment]
只需要修改net.py第225、226行即可：
`block = Bottleneck`
` self.bkbone = ResNet(block, [3, 4, 6, 3])`
另外在第123行改为相应的ResNet-50的预训练模型路径。

**Comment by fupiao1998** [comment]
感谢回复，问题已经解决，谢谢
